### ISSUE TITLE
Case-sensitive search.

### ISSUE THREAD

**Issue by streeck** [iankronquist/y-cloninator#1]
I tried searching for 'python' and it did not return any results. When I tried 'Python' instead, it worked...

I think it would be nice to have case-insensitive search for language filtering.

**Comment by codelitt** [comment]
Came here to report this as well. 

Looks like the culprit is either here where the filter is set: https://github.com/iankronquist/y-cloninator/blob/master/routes.js#L16

Looks like when the import of the project happens though, it also pulls in with the case: https://github.com/iankronquist/y-cloninator/blob/master/backend.js#L46

I'm pretty unfamiliar with express, but just a quick guess.

**Comment by lkhamsurenl-zz** [comment]
+1

**Comment by tschuy** [comment]
On it!

**Comment by tschuy** [comment]
I've pushed a fix to this and #2 to production. @iankronquist can you review #3 ?
