### ISSUE TITLE
Filtering by C# is not working

### ISSUE THREAD

**Issue by aloisdg** [iankronquist/y-cloninator#10]
Hello,

Filtering by JavaScript is working but not C#. C# display C project. I guess the `#` is not well encoded or you filter support only letter.

Cheers,

**Comment by tschuy** [comment]
I wrote a big long reply speculating it was Postgres dropping it because of **reasons** but now I realize it's because we're not url encoding the search paramters, meaning your browser treats "/C#" as "/C" with a location on the page of "#".

I'll get a fix for this sometime in the next few hours, or if you want you can fix it yourself, since I'm currently working on something else.

Thanks for the bug report!

**Comment by aloisdg** [comment]
You are welcome. :)

[Working link](http://ycloninator.herokuapp.com/C%23) for everybody else.

**Comment by tschuy** [comment]
Fixed by #12 , will close when that's merged to master. I'm pushing it to prod right now.

**Comment by aloisdg** [comment]
Cool !
